import { auth, db, provider, collection, addDoc, doc, getDoc, serverTimestamp, signInWithPopup, signOut, onAuthStateChanged } from './js/firebase.js';
import { CATALOG, DEFAULT_EXTRA_PERCENT } from './js/catalog.js';

const state = { user:null, program:null, teacherName:'', level:null, ibLevel:null, subject:null, tests:[] };
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
function showLogin(message='') { $('#login-panel').hidden=false; $('#app').hidden=true; $('#login-message').textContent=message; }
function showApp() { $('#login-panel').hidden=true; $('#app').hidden=false; $('#auth-status').textContent=state.user?.email||'Docente autenticado'; }
function setMessage(text,error=false){ const el=$('#save-message'); if(el){el.textContent=text;el.style.color=error?'#a33a3a':'';} }
function extraFor(minutes,percent){ return Math.round(minutes*percent/100); }
function resetForm(){ state.teacherName=''; state.level=null; state.ibLevel=null; state.subject=null; state.tests=[]; $('#teacher-name').value=''; $$('.choice').forEach(x=>x.classList.remove('selected')); $('#ib-level').value=''; $('#ib-level-wrap').hidden=true; $('#subject-section').hidden=true; $('#tests-section').hidden=true; $('#success-section').hidden=true; $('#tests-list').innerHTML=''; $('#save').disabled=true; setMessage(''); }
function renderProgram(){ $('#program-context').textContent=`Programación activa: ${state.program.cursoLectivo} · Periodo ${state.program.periodo} · Pruebas ${state.program.numeroPruebas}`; }
function renderSubjects(level,ibLevel=null){
  const grid=$('#subject-grid'); grid.innerHTML='';
  if(level==='11'){
    const groups=[['NS','Nivel Superior (NS)'],['NM','Nivel Medio (NM)'],['general','Otras pruebas de 11.º']];
    groups.forEach(([key,label])=>{const subjects=CATALOG['11'][key]||{};if(!Object.keys(subjects).length)return;const heading=document.createElement('h3');heading.className='subject-group-title';heading.textContent=label;grid.appendChild(heading);Object.keys(subjects).forEach(subject=>{const b=document.createElement('button');b.type='button';b.className='subject';b.textContent=subject;b.addEventListener('click',()=>selectSubject(subject,b,key==='general'?null:key));grid.appendChild(b);});});
  }else{Object.keys(CATALOG[level][ibLevel]||{}).forEach(subject=>{const b=document.createElement('button');b.type='button';b.className='subject';b.textContent=subject;b.addEventListener('click',()=>selectSubject(subject,b,ibLevel));grid.appendChild(b);});}
  $('#subject-section').hidden=false;
}
function selectLevel(level,button){ state.level=level;state.ibLevel=null;state.subject=null;$$('.choice').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');$('#ib-level-wrap').hidden=level!=='12';$('#subject-section').hidden=false;$('#tests-section').hidden=true;$('#success-section').hidden=true;$('#subject-grid').innerHTML='';if(level==='11')renderSubjects('11'); }
function selectSubject(subject,button,ibLevel=null){ state.subject=subject;state.ibLevel=ibLevel;$$('.subject').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');const catalogLevel=state.level==='12'?state.ibLevel:ibLevel;state.tests=CATALOG[state.level][catalogLevel][subject];renderTests(); }
function renderSelectedSubject(){const existing=$('#selected-subject');if(existing)existing.remove();const box=document.createElement('div');box.id='selected-subject';box.className='selected-subject';const levelText=state.ibLevel?`Nivel ${state.ibLevel}`:(state.level==='11'?'11.º':'');box.innerHTML=`<div class="selected-subject-label">Materia seleccionada</div><div class="selected-subject-name">${state.subject}</div>${levelText?`<div class="selected-subject-level">${levelText}</div>`:''}`;$('#tests-section .section-heading').insertAdjacentElement('afterend',box);}
function renderTests(){const list=$('#tests-list');list.innerHTML='';renderSelectedSubject();state.tests.forEach(test=>{const card=document.createElement('article');card.className='test-card';const suggested=test.minutes;card.innerHTML=`<div class="test-main"><input class="test-check" type="checkbox" data-id="${test.id}"><div><div class="test-name">${test.name}</div><div class="test-meta">Tiempo sugerido: ${suggested===null?'no definido':suggested+' min'}</div></div></div><div class="test-options"><label>Tiempo a utilizar (min)<input class="number-input duration" type="number" min="1" step="1" value="${suggested??''}" placeholder="Ingrese minutos"></label><label>Porcentaje adicional<input class="number-input percent" type="number" min="0" max="200" step="1" value="${DEFAULT_EXTRA_PERCENT}"></label></div><label class="support"><input class="support-check" type="checkbox"> Considerar tiempo adicional para estudiantes que requieren este apoyo</label><div class="calc">Tiempo adicional: <strong class="extra">0 min</strong> · Tiempo para planificación: <strong class="total">—</strong></div>`;const check=card.querySelector('.test-check'),duration=card.querySelector('.duration'),percent=card.querySelector('.percent'),support=card.querySelector('.support-check'),extra=card.querySelector('.extra'),total=card.querySelector('.total');function refresh(){const d=Number(duration.value)||0,p=Number(percent.value)||0,e=support.checked?extraFor(d,p):0;extra.textContent=`${e} min`;total.textContent=d?`${d+e} min`:'—';card.classList.toggle('selected',check.checked);$('#save').disabled=!$$('.test-check:checked').length;}[check,duration,percent,support].forEach(x=>x.addEventListener('input',refresh));check.addEventListener('change',refresh);list.appendChild(card);refresh();});$('#tests-section').hidden=false;$('#success-section').hidden=true;}
async function saveSelected(){setMessage('Guardando…');$('#save').disabled=true;try{state.teacherName=$('#teacher-name').value.trim();if(!state.teacherName)throw new Error('Indique su nombre antes de guardar.');if(!state.program?.id)throw new Error('No hay una programación activa.');const selected=[];$$('.test-card').forEach(card=>{if(!card.querySelector('.test-check').checked)return;const test=state.tests.find(t=>t.id===card.querySelector('.test-check').dataset.id);const duration=Number(card.querySelector('.duration').value);const support=card.querySelector('.support-check').checked;const percent=Number(card.querySelector('.percent').value)||0;if(!Number.isInteger(duration)||duration<1)throw new Error(`Indique un tiempo válido para ${test.name}.`);const extra=support?extraFor(duration,percent):0;selected.push({testId:test.id,componente:test.name,duracionSugeridaMinutos:test.minutes,duracionMinutos:duration,usaTiempoExtra:support,porcentajeExtra:support?percent:0,minutosExtra:extra,minutosPlanificacion:duration+extra});});if(!selected.length)throw new Error('Seleccione al menos una prueba.');const submissionId=`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;await Promise.all(selected.map(item=>addDoc(collection(db,'solicitudesPruebas'),{programacionId:state.program.id,cursoLectivo:state.program.cursoLectivo,periodo:state.program.periodo,numeroPruebas:state.program.numeroPruebas,submissionId,docenteId:state.user.uid,docenteEmail:state.user.email||'',docenteNombre:state.teacherName,nivel:state.level,nivelIB:state.ibLevel||null,materia:state.subject,...item,estado:'registrada',createdAt:serverTimestamp(),updatedAt:serverTimestamp()})));$('#success-message').textContent=`Se registraron ${selected.length} prueba${selected.length===1?'':'s'} de ${state.subject}`;$('#success-section').hidden=false;$('#tests-section').hidden=true;setMessage('');}catch(error){console.error(error);setMessage(error.message||'No fue posible guardar el registro.',true);$('#save').disabled=false;}}
async function loadActiveProgram(){const active=await getDoc(doc(db,'configuracion','activeProgram'));if(!active.exists()||!active.data().programacionId)return null;const id=active.data().programacionId,p=await getDoc(doc(db,'programaciones',id));if(!p.exists()||p.data().estado!=='abierta')return null;return {id:p.id,...p.data()};}
$('#login-google').addEventListener('click',async()=>{try{await signInWithPopup(auth,provider);}catch(error){console.error(error);$('#login-message').textContent=`No fue posible iniciar sesión: ${error.code||error.message}`;}});$('#logout').addEventListener('click',()=>signOut(auth));$$('.choice').forEach(b=>b.addEventListener('click',()=>selectLevel(b.dataset.level,b)));$('#ib-level').addEventListener('change',e=>{state.ibLevel=e.target.value;state.subject=null;$('#tests-section').hidden=true;if(state.ibLevel)renderSubjects('12',state.ibLevel);else $('#subject-section').hidden=true;});$('#save').addEventListener('click',saveSelected);$('#reset').addEventListener('click',()=>{state.subject=null;state.tests=[];$('#tests-section').hidden=true;setMessage('');});$('#another').addEventListener('click',()=>resetForm());$('#finish').addEventListener('click',()=>{resetForm();window.scrollTo({top:0,behavior:'smooth'});});
onAuthStateChanged(auth,async user=>{state.user=user||null;if(!user){$('#auth-status').textContent='No autenticado';showLogin();return;}try{state.program=await loadActiveProgram();if(!state.program){showApp();$('#app').innerHTML='<section class="card"><h1>No hay una programación abierta</h1><p class="muted">El administrador aún no ha abierto una programación de pruebas.</p></section>';return;}renderProgram();showApp();}catch(error){console.error(error);showApp();$('#app').innerHTML='<section class="card"><h1>No fue posible cargar la programación</h1><p class="muted">Revise la conexión o las reglas de acceso.</p></section>';}});
